---
title: "NA-POPS: collaborators"
---

## Primary Collaborators

We are a group of researchers associated with the Canadian Wildlife Service (CWS), Boreal Avian Modeling Project (BAM), Canadian Forest Service (CFS), Partners in Flight Science Committee (PIF), and we are actively seeking to develop a broader network.

We welcome additional collaborators that can contribute substantially to scientific manuscripts. If you are interested in a more in-depth collaboration, please see our [collaboration guidelines](https://docs.google.com/document/d/1fJCGK8MCSqPAO51VUZbJcp2HBPsgIMT51xswLL53rpk/edit?usp=sharing), and contact us to assess opportunities to contribute.

## Data Providers

Our goal will only be possible with many contributions and with large volumes of data. We will of course, provide formal acknowledgments of all contributed data in the products that stem from this work. It would be impractical to offer co-authorship to all data providers, simply due to the sheer number of datasets required to achieve our goal.
